TUPLES

Create a tuple, called "Cars", with elements "BMW", "Dodge", and "Ford". 

In [1]:
Cars = ("BMW", "Dodge", "Ford")

Access the second element of this tuple.

In [2]:
print(Cars[1])

Dodge


Call a method that would allow you to extract the provided name and age separately. Then print the "name" and "age" values to see if you worked correctly.

In [3]:
data = 'Peter,24' #original string

name, age = data.split(',') #split the string into a list based on the comma
print("Name:", name)
print("Age:", age)

Name: Peter
Age: 24


Create a function that takes as arguments the two values of a rectangle and then returns the Area and the Perimeter of the rectangle.
Call the function with arguments 2 and 10 to verify it worked correctly.

In [4]:
def rectangle(width, height):
    area= width*height
    perimeter= 2*(width+height)
    return area, perimeter
area, perimeter= rectangle(2,10)
print("Area: ", area)
print("Perimeter: ", perimeter)

Area:  20
Perimeter:  24


FOR LOOPS

Create a for loop that prints every digit on a new line.

In [5]:
digits = [0,1,2,3,4,5,6,7,8,9]

for digit in digits:
  print(digit)

0
1
2
3
4
5
6
7
8
9


Adjust the code, so the digits are all printed on the same line.

In [6]:
for digit in digits:
  print(digit, end='')

0123456789

DICTIONARIES

This is the menu of a close restaurant:

In [7]:
Menu = {
    'meal_1': 'Spaghetti',
    'meal_2': 'Fries',
    'meal_3': 'Hamburger',
    'meal_4': 'Lasagna'}

What is the second meal in the list?

In [8]:
Menu["meal_2"]

'Fries'

Add a new meal- "Soup".

In [9]:
Menu['meal_5'] = 'Soup'
Menu

{'meal_1': 'Spaghetti',
 'meal_2': 'Fries',
 'meal_3': 'Hamburger',
 'meal_4': 'Lasagna',
 'meal_5': 'Soup'}

Replace the Hamburger with a Cheeseburger

In [10]:
Menu.update({'meal_3' : 'Cheeseburger'})
Menu

{'meal_1': 'Spaghetti',
 'meal_2': 'Fries',
 'meal_3': 'Cheeseburger',
 'meal_4': 'Lasagna',
 'meal_5': 'Soup'}

Add the Desserts list in the form of sixth meal.

In [11]:
Dessert = ['Pancakes', 'Icecream', 'Tiramisu']
Menu['meal_6']= Dessert
Menu

{'meal_1': 'Spaghetti',
 'meal_2': 'Fries',
 'meal_3': 'Cheeseburger',
 'meal_4': 'Lasagna',
 'meal_5': 'Soup',
 'meal_6': ['Pancakes', 'Icecream', 'Tiramisu']}

Create a new dictionary that contains the first five meals as keys and assign the following five values as prices (in dollars):
10, 5, 8, 12, 5. 
Start by *Price_list = {}*.

In [12]:
Price_list = {}
meals = ['meal_1', 'meal_2', 'meal_3', 'meal_4', 'meal_5']
prices = ['$10', '$5', '$8', '$12', '$5']

for i in range(len(meals)):
  Price_list[meals[i]] = prices[i]

Price_list

{'meal_1': '$10',
 'meal_2': '$5',
 'meal_3': '$8',
 'meal_4': '$12',
 'meal_5': '$5'}

Use the get method to check the price of spaghetti.

In [13]:
Price_list.get('meal_1')

'$10'

LIST SLICING

In [14]:
Numbers = [15, 40, 50, 100, 115, 140]

Using list slicing, obtain the numbers 100 and 115.

In [15]:
slicing = Numbers[3:5]
slicing

[100, 115]

Using slicing, extract the first four elements from the list.

In [16]:
slicing = Numbers[ :4]
slicing

[15, 40, 50, 100]

Using slicing, extract all the elements from the list from the 3rd position onwards.

In [17]:
slicing = Numbers[2: ]
slicing

[50, 100, 115, 140]

Using slicing, extract the last 4 elements from the list.

In [18]:
slicing = Numbers[-4: ]
slicing

[50, 100, 115, 140]

Which is the position of the value 15?

In [19]:
position = Numbers.index(15)
position

0

Create a list, called "Two_Numbers". Let its elements be the values 1 and 2. Then, create a new one, named "All_Numbers", that will containt both the "Numbers" and the "Two_Numbers" lists. 

In [20]:
Two_Numbers = [1,2]
Numbers = [3,4,5]

Two_Numbers = Two_Numbers + Numbers
Two_Numbers

[1, 2, 3, 4, 5]

Sort all the numbers in the "Numbers" list from the largest to the smallest.

In [21]:
Two_Numbers.sort(reverse = True)
Two_Numbers

[5, 4, 3, 2, 1]

HELP YOURSELF WITH METHODS

In [22]:
Numbers = [15, 40, 50]

Append the number 100 to the Numbers list.

In [23]:
Numbers.append(100)
Numbers

[15, 40, 50, 100]

With the help of the "extend method", add the numbers 115 an 140 to the list. 

In [24]:
Numbers.extend([115,140])
Numbers

[15, 40, 50, 100, 115, 140]

Print a statement, saying "The fourth element of the Numbers list is:" and then designate the value of the fourth element. Use a trailing comma.

In [25]:
print('The fourth element of the Numbers list is:', Numbers[3], end=',')

The fourth element of the Numbers list is: 100,

How many elements are there in the Numbers list?

In [26]:
elements = len(Numbers)
print('The number of elements in the number list is:', elements)

The number of elements in the number list is: 6


WHILE LOOPS AND INCREMENTING

Create a while loop that will print all odd numbers from 0 to 30 on the same row. 
<br />
*Hint: There are two ways in which you can create the odd values!*

In [27]:
num = 1 #initialize the variable with the first odd number
while num <= 30: #loop until number is greater than 30
    print(num, end=' ') #print the current number without moving to a new line
    num += 2     #increment number by 2 to get the next odd number

1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 

CREATE A LIST WITH THE RANGE FUNCTION

Use the range() function to create a list with all numbers from 1 to 10.

In [28]:
numbers = list(range(1,11))
print(numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


Use the range() function to create a list with all numbers from 0 to 19.

In [29]:
numbers = list(range(0,20))
print(numbers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


Use the range function to create a list with all even numbers from 0 to 30 included.

In [30]:
even_num = list(range(0,31,2))
print(even_num)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]


USE CONDITIONAL STATEMENTS AND LOOPS TOGETHER

Create a For loop that will print all the variables from a given list multiplied by 2. Let the list contain all numbers from 1 to 10. Create it with the help of the range() function.

In [31]:
numbers = list(range(1,11))
for num in numbers:
    print(num * 2,end=' ')

2 4 6 8 10 12 14 16 18 20 

Create a little program that runs a loop over all values from 1 to 30. Let it print all Odd numbers, and in the place of the even numbers, it should print "Even".
Help yourself with the range() function to solve this exercise.

In [32]:
for num in range(1,31): #loop through numbers from 1 to 30
    if num % 2 == 0:
        #print "Even" for even numbers
        print("Even", end=' ')
    else:
        #print the number for odd numbers
        print(num, end=' ')

1 Even 3 Even 5 Even 7 Even 9 Even 11 Even 13 Even 15 Even 17 Even 19 Even 21 Even 23 Even 25 Even 27 Even 29 Even 

You have the following list of numbers. Iterate over this list, printing out each list value multiplied by 10.
Find two solutions of this problem.

In [47]:
n = [1,2,3,4,5,6]

In [35]:
for num in n:
    print(num*10)

10
20
30
40
50
60


In [ ]:
n = [1,2,3,4,5,6]
[print(num *10) for num in n]
OUTPUT
[print(num *10) for num in n]

10
20
30
40
50
60
